# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Algolab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   # ignore all warnings from all pods
   inhibit_all_warnings!

  # Pods for Algolab
  pod 'Moya', '~> 14.0'
  pod "PromiseKit", "~> 6.8"
  pod 'Swinject'
  pod 'lottie-ios'

  target 'AlgolabTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'Nimble'
  end

  target 'AlgolabUITests' do
    # Pods for testing
  end

end
